kind: ConfigMap
apiVersion: v1
metadata:
  name: istio-ca-root-cert
  labels:
    istio.io/config: 'true'
data:
  root-cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIIC/TCCAeWgAwIBAgIRAP5RehCdNpye7j8mpML+0NQwDQYJKoZIhvcNAQELBQAw
    GDEWMBQGA1UEChMNY2x1c3Rlci5sb2NhbDAeFw0yNTA2MjAwODE3MDVaFw0zNTA2
    MTgwODE3MDVaMBgxFjAUBgNVBAoTDWNsdXN0ZXIubG9jYWwwggEiMA0GCSqGSIb3
    DQEBAQUAA4IBDwAwggEKAoIBAQC4Oip+TfNu7fRqkGxonXxrL7bVRFIk+8v641Vx
    teoLn0SuWYWWpSSHXHVBuFgsGXyeJBMWf/aEn9pjIXzS5I9pfP1sEmuOmLMw06AT
    eYrIIN5jqOffFGqFkfvIrWTSlynpBI8qP5fncKd2GuIpFpbk5HMI1xsZxuIBabWo
    W7znC0JF6y+Q4M7iEnUFpZmhU2V9rfbhtSBiPU59f51j2iTCCzllVk/5NDlKzO6Z
    faTJYSFN116KqpPjfi/XcdEEI/BBFWvYu5Jg8bFUOUhvxHQCJg7ZFY66I7kRiB3i
    UA4ZFYRJR9oYqg2AphLmRTTOJMl+/6tySjBkhNJu34mjMLktAgMBAAGjQjBAMA4G
    A1UdDwEB/wQEAwICBDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQnVRuap+Gz
    QUp9W0yl/vBUquoY4TANBgkqhkiG9w0BAQsFAAOCAQEAfoSSPGUO+ZoIVZGdgI8+
    +S8pWbneBd+DS7zItjp1YelmCgaCfoQ5YNjeUjVRlGUDu0alAh5gJBmivJ6atrjN
    mxYsv2XolsUZxJPxxKmEbXvQ2EpnlLWT90DX4r25az2RgzsH+mun7HEefUiqdgn2
    ASXJorQaZUW23K+psR0IR7UTHWQ6iZdRe519Oqs0JK4l4y4NZxmKsiNkjX/p1alw
    whhzm479J5AD3dyQ7QItSKEqAe7hkrGMe+dUz5isCH4ECFX96bOaCS9tMWlA76kJ
    20ECzd8n2Tz00PiUC/lI2apEKTDqxp031fh74hB1Zq0T5xx0F1k80VuoSKZDYRVT
    Iw==
    -----END CERTIFICATE-----
